[project]
name = "made"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Leonardo Baroncelli", email = "leonardo.baroncelli.ext@leonardo.com" },
    { name = "Francesco Bernardi", email = "francesco.bernardi01@leonardo.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy<2",
    "torch",
    "transformers>=4.29.0",
    "ray[data,default]>=2.40.0",
    "webdataset",
    "nltk",
    "fasttext>=0.9.2",
    "spacy[cuda12x]",
    "Pillow>=11.1.0",
    "imageio",
    "easyocr",
    "faiss-gpu-cu12",
    "pytest",
    "pytest-cov"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"