[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fair_spoke_8_leonardo"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.8"
]
<<<<<<< Updated upstream
authors = [
    {name = "Leonardo Baroncelli", email = "leonardo.baroncelli26@gmail.com"},
    {name = "Francesco Bernardi", email = ""},
    {name = "Pietro Bongini", email = ""},
    {name = "Fabio Di Matteo", email = ""},
    {name = "Giancarlo Paoletti", email = ""},

=======
download = [
    "fastparquet>=2024.11.0",
    "huggingface-hub==0.13.4",
    "img2dataset>=1.45.0",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.4",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
>>>>>>> Stashed changes
]
maintainers = [
    {name = "Leonardo Baroncelli", email = "leonardo.baroncelli26@gmail.com"},
    {name = "Francesco Bernardi", email = ""},
    {name = "Pietro Bongini", email = ""},
    {name = "Fabio Di Matteo", email = ""},
    {name = "Giancarlo Paoletti", email = ""}
]

dependencies = [
    "transformers",
    "datasets",
    "accelerate",
    "tqdm",
    "img2dataset"
]

[project.optional-dependencies]
dev = [
    
]

[project.urls]
"Repository" = "https://github.com/LeoBaro/fair_spoke_8"
"Issues" = "https://github.com/LeoBaro/fair_spoke_8/issues"
