import re
import logging
from pathlib import Path
import shutil

import ray
import numpy as np

from made.config import Config
from made.data_pipeline.common.metrics_store import MetricsStore
from made.data_pipeline.common.singleton import Singleton

""" collection of stateless utility functions """
def remove_and_recreate_dirs(dirs):
    for d in dirs:
        path = Path(d)
        if path.exists():
            shutil.rmtree(path)
        path.mkdir(parents=True, exist_ok=True)

def connect_or_start_ray(ray_address, logging_level, log_to_driver, log_folder, ray_object_store_memory):
    if ray_address:
        ray.init(
            address=ray_address,
            logging_level=getattr(logging, logging_level),
            log_to_driver=log_to_driver
        )
    else:
        ray.init(
            logging_level=getattr(logging, logging_level),
            log_to_driver=log_to_driver,
            object_store_memory=ray_object_store_memory
        )
    logger = logging.getLogger("ray")
    logger.info("Setting up logging to %s", log_folder / "ray_log.log")
    logger.addHandler(logging.FileHandler(log_folder / "ray_log.log"))
    # formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
 
def cleanup():
    logging.getLogger("ray").info("Cleaning up..")
    shutdown_ray()
    Singleton.destroy_instance(Config)

def collect_tar_files(shards_path: list[str | Path], recursive: bool = False):
    if recursive:
        tar_files = sorted([str(s) for s in Path(shards_path).glob("**/*.tar")])
    else:
        tar_files = sorted([str(s) for s in Path(shards_path).glob("*.tar")])

    logging.getLogger("ray").info("Found %d tar files from %s", len(tar_files), shards_path)
    
    if len(tar_files) == 0:
        raise ValueError(f"No tar files found in {shards_path}")
    return tar_files

def get_worker_id():
    return ray.get_runtime_context().get_worker_id() if ray.is_initialized() else "local"

def shutdown_ray():
    logger = logging.getLogger("ray")

    logger.info("Shutting down Ray")
    if ray.is_initialized():
        ray.shutdown()  
    else:
        logger.info("Ray is not initialized. Skipping shutdown")

def save_uids(uids: list[str], output_folder: str | Path):
    """
    The format describing the subset of samples should be a numpy array of dtype 
    numpy.dtype("u8,u8") (i.e. a structured array of pairs of unsigned 64-bit integers), 
    with shape (subset_size,), containing a list of uids (128-bit hashes from the parquet 
    files) in lexicographic sorted order, saved to disk in either npy format or 
    memory-mapped format.    
    """
    output_folder = Path(output_folder)
    output_folder.mkdir(parents=True, exist_ok=True)
    out_filename = output_folder / "good_uids.npy"
    processed_uids = np.array([(int(uid[:16], 16), int(uid[16:32], 16)) for uid in uids], np.dtype("u8,u8"))
    processed_uids.sort()
    np.save(out_filename, processed_uids)
    return out_filename

def rename_thread_files(directory_path):
    """
    Rename tar files generated by different threads to sequential numbering.
    
    Args:
        directory_path (str): Path to the directory containing the files
        
    Returns:
        dict: Mapping of old filenames to new filenames
    """
    directory = Path(directory_path)
    
    if not directory.exists():
        raise FileNotFoundError(f"Directory {directory_path} does not exist")
    
    # Pattern to match tar files with thread suffix
    tar_pattern = re.compile(r'^(.+)_(\d{8})\.tar$')
    
    # Find all tar files and extract their information
    tar_files = []
    for file in directory.iterdir():
        if file.is_file() and file.suffix == '.tar':
            match = tar_pattern.match(file.name)
            if match:
                prefix = match.group(1)
                thread_num = int(match.group(2))
                tar_files.append({
                    'original_name': file.name,
                    'full_path': file,
                    'prefix': prefix,
                    'thread_num': thread_num
                })
    
    if not tar_files:
        print("No tar files found matching the pattern")
        return {}
    
    # Sort files by thread number to maintain order
    tar_files.sort(key=lambda x: x['thread_num'])
    
    # Rename files sequentially
    rename_map = {}
    for i, file_info in enumerate(tar_files):
        old_path = file_info['full_path']
        new_name = f"{i:08d}.tar"
        new_path = directory / new_name
        
        # Check if target file already exists
        if new_path.exists() and new_path != old_path:
            print(f"Warning: Target file {new_name} already exists, skipping {file_info['original_name']}")
            continue
        
        try:
            old_path.rename(new_path)
            rename_map[file_info['original_name']] = new_name
            print(f"Renamed: {file_info['original_name']} -> {new_name}")
        except OSError as e:
            print(f"Error renaming {file_info['original_name']}: {e}")
    
    return rename_map

def set_plotting_configuration():
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set_style("whitegrid")
    sns.set_context("paper")

    plt.rcParams.update({
        'font.size': 16,                # Base font size
        'axes.titlesize': 18,           # Title size
        'axes.labelsize': 16,           # Axis label size
        'xtick.labelsize': 14,          # X-tick label size
        'ytick.labelsize': 14,          # Y-tick label size
        'legend.fontsize': 14,          # Legend font size

        'figure.figsize': [6.4, 4.8],   # Default figure size (in inches)
        'savefig.dpi': 300,             # High resolution for saved images
        'axes.grid': True,              # Enable grid
        'grid.alpha': 0.3,              # Grid transparency
        'axes.spines.top': False,       # Remove top spine
        'axes.spines.right': False,     # Remove right spine

        'lines.linewidth': 2,           # Thicker lines
        'lines.markersize': 6,          # Moderate marker size

        'legend.frameon': False,        # Remove legend frame

        'text.usetex': False,           # Set to True if using LaTeX rendering
    })
    plt.rcParams['figure.autolayout'] = True
