infrastructure:
  enable_metrics: true
  save_bad_uids: false
  logging_level: DEBUG
  log_to_driver: true
  apply_filters: true
  

unimodal_text:
  num_workers: 1
  batch_size: 4000

  caption_min_words: 2
  caption_min_chars: 5

  lang_detection_model_path: models/lid.176.bin
  lang_detection_score_threshold: 0.7
  lang_detection_language: en

  tagging_model_name: en_core_web_trf
  good_captions_pos_distribution_path: models/common_pos_patterns.txt

unimodal_vision:
  num_workers: 1 
  batch_size: 500

  image_min_aspect_ratio: 0.8
  image_max_aspect_ratio: 3.0
  image_min_dimension: 50

  text_threshold: 0.6
  text_detection_model_path: models
  text_detection_mag_ratio: 0.5
  
multimodal:
  num_workers: 1 
  batch_size: 256

  dfn_model: leobaro/DFN-public
  dfn_percentile_to_drop: 25
  clip_caption_max_length: 77

specificity:
  batch_size: 500
  
  model_path: models/ckpt.pt
  reference_path: models/reference.pt
  
  specificity_threshold: 0.25
  curvature: 1.0