infrastructure:
  num_nodes: 2
  num_workers: 8 
  webdataset: /home/leobaro/Downloads/datasets/web/datacomp
  enable_timing: true

unimodal:
  batch_size: 4000

  caption_min_length: 10
  caption_max_length: 100

  lang_detection_model_path: models/lid.176.bin
  lang_detection_score_threshold: 0.7
  lang_detection_language: en

  tagging_model_path: models/blabla.bin
  good_captions_pos_distribution_path: models/blabla.pickle

  aspect_ratio_threshold: 3.0



multimodal:
  batch_size: 32
  clip_processor: "openai/clip-vit-base-patch32"
  clip_model: "openai/clip-vit-base-patch32"
  caption_generation_processor: "llava-hf/llava-v1.6-mistral-7b-hf"
  caption_generator_model: "llava-hf/llava-v1.6-mistral-7b-hf"
  diffusion_model: ""
  clip_score_threshold: 0.5

