unimodal:
  batch_size: 32
  caption_min_length: 10
  caption_max_length: 100
  aspect_ratio_threshold: 3.0

multimodal:
  batch_size: 32
  clip_processor: "openai/clip-vit-base-patch32"
  clip_model: "openai/clip-vit-base-patch32"
  caption_generation_processor: "llava-hf/llava-v1.6-mistral-7b-hf"
  caption_generator_model: "llava-hf/llava-v1.6-mistral-7b-hf"
  diffusion_model: ""
  clip_score_threshold: 0.5

infrastructure:
  num_nodes: 10
  webdataset: /home/leobaro/Downloads/datasets/web/datacomp